#swagger based on https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-2-the-basics/
#this is the Open API version which we use
swagger: "2.0"
#Info about our api, this version es the api's version (not the specification version or the file version)
info:
  version: 1.0.0
  title: Api CRUD for user's videos
  description: A simple Api which only can be access by token
  contact:
    name: Fernando Llallire
    email: fernandorllallire@gmail.com
#info of the URL which people will use to call the web api
schemes:
  #- https
  - http
host: localhost:3030
basePath: /video/api
securityDefinitions:
  myCookie:
    type: apiKey
    name: Cookie
    in: header
#list -> videocontroller.findall
#add -> videocontroller.add
#delete -> videocontroller.delete
#update -> videocontroller.update
paths:
  /list:
    get:
      security:
        - myCookie: []
      description: list all the videos of the user logged
      responses:
        200:
          description: show all url and description of each video 
          schema: 
            type: array
            items:
              type: object
              required:
                - url
                - description
              properties:
                url:
                  type: string
                  description: Url del video
                description:
                  type: string
                  description: descripcion del video

        500:
          description: An unexpected error ocured
          schema:
            $ref: "#/definitions/Error"
  /add:
   put:
    security:
      - myCookie: []
    description: add url and description of a new video to user
    parameters:
      - name: New video parameters
        in: body
        required: true
        description: url and description of the new video
        schema:
          required:
            - url
            - description
          properties:
            url:
              type: string
            description:
              type: string
    responses:
      200:
        description: video added
        schema:
          type: object
          required:
            - message
            - data
          properties:
            message:
              type: string
              description: mensaje de estado del mensaje
            data:
              type: array
              items:
                required:
                  - url
                  - description
                properties:
                  url:
                    type: string
                    description: url of the new video
                  description:
                    type: string
                    description: description of the new video
      500:
        description: An unexpected error ocured
        schema:
          $ref: "#/definitions/Error"

  /update:
      patch:
        security:
          - myCookie: []
        description: add url and description of a new video to user
        parameters:
          - name: video parameters to update
            required: true
            in: body
            description: url and description of the video and the new parameters
            schema:
              required:
                - url
                - description
                - newUrl
                - newDescription
              properties:
                url:
                  type: string
                description:
                  type: string
                newUrl:
                  type: string
                newDescription:
                  type: string
        responses:
          200:
            description: video updated
            schema:
              type: object
              required:
                - message
                - data
              properties:
                message:
                  type: string
                data:
                  type: array
                  items:
                    required:
                      - url
                      - description
                    properties:
                      url:
                        type: string
                        description: url of the old video
                      description:
                        type: string
                        description: description of the old video
          500:
            description: An unepected error ocured
            schema:
              $ref: "#/definitions/Error"
                  
  /delete:
    delete:
      security:
        - myCookie: []
      description: add url and description of the video to delete
      parameters:
        - name: Delete Video Parameters
          required: true
          in: body
          description: id of the elemento to delete
          schema:
            required:
              - id
            properties:
              id:
                type: string
      responses:
        200:
          description: video deleted
          schema:
            type: object
            required:
              - message
              - data
            properties:
              message:
                type: string
              data:
                type: array
                items:
                  required:
                    - url
                    - description
                  properties:
                      url:
                        type: string
                        description: url of the delected video
                      description:
                        type: string
                        description: description of the delected video
        500:
          description: An unepected error ocured
          schema:
            $ref: "#/definitions/Error" 
            
definitions:
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
