#swagger based on https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-2-the-basics/
#this is the Open API version which we use
swagger: "2.0"
#Info about our api, this version es the api's version (not the specification version or the file version)
info:
  version: 1.0.0
  title: Api CRUD for user's videos
  description: A simple Api which only can be access by token
  contact:
    name: Fernando Llallire
    email: fernandorllallire@gmail.com
#info of the URL which people will use to call the web api
schemes:
  #- https
  - http
host: localhost:3030
basePath: /video/api
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /list:
    get:
      security:
        - Bearer: []
      description: list all the videos of the user logged
      responses:
        200:
          description: Show an array with all the videos of the user
          schema:
            $ref: "#/definitions/VideoResponse" 
        500:
          description: An unexpected error ocured
          schema:
            $ref: "#/definitions/Error"
  /add:
   put:
    security:
      - Bearer: []
    description: add url and description of a new video to user
    parameters:
      - name: New video parameters
        in: body
        required: true
        description: url and description of the new video
        schema:
          $ref: "#/definitions/BodyVideoParameters" 
    responses:
      200:
        description: Message of the status and an array with all the new videos
        schema:
          $ref: "#/definitions/TypeResponseVideo" 
              
      500:
        description: An unexpected error ocured
        schema:
          $ref: "#/definitions/Error"

  /update:
      patch:
        security:
          - Bearer: []
        description: add url and description of a new video to user
        parameters:
          - name: video parameters to update
            required: true
            in: body
            description: url and description of the video and the new parameters
            schema:
              required:
                - _id
                - url
                - description
                - newUrl
                - newDescription
              properties:
                _id:
                  type: string
                url:
                  type: string
                description:
                  type: string
                newUrl:
                  type: string
                newDescription:
                  type: string
        responses:
          200:
            description:  Message of the status and an array with all the new videos
            schema:
             $ref: "#/definitions/TypeResponseVideo"
          500:
            description: An unepected error ocured
            schema:
              $ref: "#/definitions/Error"
                  
  /delete:
    delete:
      security:
        - Bearer: []
      description: add url and description of the video to delete
      parameters:
        - name: Delete Video Parameters
          required: true
          in: body
          description: id of the elemento to delete
          schema:
            $ref: "#/definitions/BodyVideoParameters" 
      responses:
        200:
          description:  Message of the status and an array with all the remaining videos
          schema:
            $ref: "#/definitions/TypeResponseVideo"
        500:
          description: An unepected error ocured
          schema:
            $ref: "#/definitions/Error" 
            
definitions:
  BodyVideoParameters:
    required:
      - _id
      - url
      - description
    properties:
      _id:
        type: string
      url:
        type: string
      description:
        type: string
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  TypeResponseVideo:
    type: object
    required:
      - message
      - data
    properties:
      message:
        type: string
        description: status of the action
      data:
        $ref: "#/definitions/VideoResponse"
  VideoResponse:
    type: array
    items:
      type: object
      required:
        - _id
        - url
        - description
      properties:
        _id:
          type: string
          description: Id of the subdocument in mongoose
        url:
          type: string
        description:
          type: string